- client/evidence.lua
- client/objects.lua
**Describe Pull request**
- Optimized closest Evidence setter
- Optimized Spike System
If your PR is to fix an issue mention that issue here
**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes
> Update: Small optimizations

- client/evidence.lua
- client/heli.lua
- client/job.lua
- client/main.lua
- client/objects.lua
- server/main.lua
**Describe Pull request**
Changed job name checks to job type checks
**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes
> Swapped job checks to type instead of name

- .github/workflows/lint.yml
- client/job.lua
- client/main.lua
- server/main.lua
**Describe Pull request**
I was only here to fix the ox_inventory problem
**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]
> Some fixes I guess

- client/interactions.lua
Check for IsLoggedIn before trying to access to the PlayerData
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes]
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]
> fix: IsLoggedIn check before PlayerData

- .github/workflows/assign.yml
- client/interactions.lua
Further abstraction of the code in PR #9
Also includes an update to .github involving a new assign function for issues.
The controls functions I extracted could be moved into the core and setup as a function since they could easily be used elsewhere.
If your PR is to fix an issue mention that issue here
**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [no] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]
> (ref) Further Abstraction of PR #9

- client/interactions.lua
- server/main.lua
tested on qb-core, expected behavior was to see the information on the item in game. That didnt work before and now does. https://imgur.com/a/Hf1m8VD
> add dna hash to description

- client/anpr.lua
- config.lua
- server/main.lua
Radars weren't that useful :c
now they really are radars (even if the file is called ANPR wich isn't really a radar i guess but who cares)
> Make Radars Great Again (MRGA)

- server/main.lua
> refactor(server/main): replacing redundant function with core one

- client/evidence.lua
- client/interactions.lua
- client/job.lua
- fxmanifest.lua
- locales/en.lua
- server/main.lua
refactor code to ox
Search inventory based on playerID
Fix fxmanifest locale
Add Policelocker registry (personnel only)
> refactor(client/server) Fix evidence

- server/main.lua
- extracted common code to reduce duplication
- fixed casing
- gate clauses and other minor refactors
> refactor(server/main): minor cleanup

- client/heli.lua
> refactor(client/heli): first pass light cleanup

- client/anpr.lua
- client/heli.lua
- client/interactions.lua
- made local function camelCased
- extracted common functions to reduce duplicate code
- more guard clauses
> refactor(client/interactions): minor cleanup

- client/evidence.lua
- server/main.lua
- reduce duplicate code
- rename variables for style compliance
- turned whitelist into boolean table instead of array for easier lookups
- sneaking in fix for server/main to put bloodType in evidence metadata again.
> refactor(client/evidence): extracting functions

- client/job.lua
- general cleanup
- reduced scope of net events to local/global functions based on usage in Qbox.
- removed menu with one option which opened evidence locker input dialog. Provided no value; just an extra click for players.
> refactor(client/job)!: cleanup, reducing scope

- server/main.lua
Fixes the error people get upon installing the recipe
> fix(server): wait for ox inventory to load sql

- client/anpr.lua
- client/evidence.lua
- client/job.lua
- config.lua
- server/main.lua
Why was this let through either way?
> Fix lint errors

- client/job.lua
> fix(client/job): Send Server Proper ID

- .vscode/settings.json
- server/commands.lua
- server/main.lua
Attempting to organize the giant server/main.lua file. This is a good grouping of code that can be split into its own file.
> refactor(server): moved commands into their own file

- client/camera.lua
- camelCased local functions 
- secured net events against being called by the client
- extracted a function to make the main camera thread's behavior more readable
> refactor(client/camera): minor improvements

- client/evidence.lua
- extracted common method for drawing evidence on the ground to reduce logic duplication
> refactor(client/evidence): extracted common method

- locales/de.lua
Oops, corrected missing commas, i don't know why they were deleted, I'll check better next time
> chore(locales): fix de.lua

- .vscode/settings.json
- client/heli.lua
- Using enums instead of booleans
- Minor function extracting
- This is untested, but should be tested before merging.
> refactor(client/heli): using enums

- server/main.lua
> it fixes the putin or out while the player dead

- client/job.lua
- Fixes #34 even through the issue outlined was no longer the actual issue, it is fixed nonetheless.
- Makes use of the config option, Config.PolyDebug.
> fix: duty toggle and add PolyDebug

- client/interactions.lua
- client/job.lua
- server/main.lua
- Fix spawning for helicopters, the impound, and the police garage
- Fix an error with the police alert needing playerSource
- Fix a typo in interactions.lua
> fix: vehicle spawning

- client/anpr.lua
- client/camera.lua
- client/evidence.lua
- client/heli.lua
- client/interactions.lua
- client/job.lua
- client/main.lua
- client/objects.lua
- client/tracker.lua
- config.lua
- fxmanifest.lua
- server/commands.lua
- server/main.lua
This is a part preparation of a larger edit. Just don't wanna do too big of a PR.
The edits are as follows:
- Standardized the use of ' over " in the resource where applicable.
- Adjust variable and local function names to camelCase.
- Fix Config.UseTarget as we don't use a convar for that.
- Unnest some config options.
> fix: style edits

- client/job.lua
- client/main.lua
- config/shared.lua
I use this modification personally, as it is good when I want to add new police stations to the server
> Complete the addresses of the police departments

- server/main.lua
Sets a default value for minGrade if the param is left blank/nil
- [ x ] My pull request fits the contribution guidelines & code conventions.
> Set default value for minGrade in IsLeoAndOnDuty

- client/main.lua
- server/main.lua
> replace ambulance to type ems

- config/server.lua
- server/commands.lua
tow and lawyer paid move config
> tow and lawyer paid move config

- config/server.lua
- server/commands.lua
Moved some code to the configuration file
> Moved some code to the configuration file

- client/interactions.lua
Needed for new implementation of cuffed whilst dead/last stand animations.
> feat(client/interactions): Handling cuff whilst dead/last stand anims.

- README.md
- server/main.lua
additionally updates the readme because none of that stuff is a dependency anymore?
qbx_management doesn't handle money anymore. Use Renewed-Banking because best banking
> refactor(server/main): use correct banking exports

- server/main.lua
> refactor: use vehicle entity from spawn function

- client/anpr.lua
- client/camera.lua
- client/evidence.lua
- client/heli.lua
- client/interactions.lua
- client/job.lua
- client/main.lua
- client/objects.lua
- html/main.css
- server/commands.lua
- server/main.lua
Part of #112
Set up global variables according to their usage
> The option to hide whitespace characters can be helpful, when looking at changes.
> refactor: whitespaces global variables and loops

- fxmanifest.lua
...chore: remove unused imported file
fixes a major issue with the server files not reading the correct config file + removed useless import from the fxmanifest
> fix/chore!: read correct config file

- client/interactions.lua
- client/job.lua
lib.playAnim is cool. Also need to release or bad things happen
> refactor(client): release anims

- client/main.lua
- config/client.lua
- config/shared.lua
Adds blip and duty toggle functionality
> feat(client): blip and duty

- client/main.lua
- config/shared.lua
Adds job management capabilities
> feat(client): management

- client/main.lua
- client/vehicles.lua
- config/shared.lua
- fxmanifest.lua
Adds vehicle spawning functionality for the garage and helipad.
> feat(client): vehicle spawning

- server/main.lua
Forgot to include this in the vehicles pr
> feat(server/main): missing spawnVehicle callback

- client/main.lua
- config/shared.lua
- server/main.lua
Adds Evidence Drawer and Personal Stash functionality
> feat: personal stash and evidence

- client/main.lua
- client/vehicles.lua
- config/shared.lua
- fxmanifest.lua
- locales/en.json
- server/commands.lua
- Adds `/callsign` and `/fine`
> feat(server/commands): callsign and fine

- client/main.lua
- fxmanifest.lua
- server/main.lua
> fix: locales, targets, and stashes

- client/main.lua
- config/server.lua
- server/main.lua
> feat: officer duty blips

- client/main.lua
- config/shared.lua
- server/main.lua
- types.lua
Just sorting types and adding some missed defaults
> feat: types

- client/main.lua
- config/shared.lua
- locales/en.json
- server/main.lua
- types.lua
- Adds armory functionality
- Fixes some types
> feat: armory

- client/main.lua
- client/vehicles.lua
- config/shared.lua
- locales/en.json
- server/main.lua
- types.lua
- Impounding and confiscation functionality
- Add radial menu options on `onResourceStart`
- Add the ability to fully customize vehicles coming from garage spawner
> feat: impounding and confiscation

- server/commands.lua
- server/main.lua
- Adds dependency checks
- Adds version checking
- Proper vehicle mods table init
> fix(server): vehicle mods and version checking

- client/vehicles.lua
- locales/en.json
- server/main.lua
- Replaced the unnecessary callbacks with server events
- Removed unnecessary callback annotations
- Adjusted some variable names
> refactor: vehicles
