client/interactions.lua

- Fix send to jail input dialog not showing input field
- Remove code of old animations dpemote (I think that was to cancel animations? scully_emote seems to be different)

fix(client): jail input dialog, remove old cancel animation

---

client/anpr.lua
client/interactions.lua
client/job.lua
server/main.lua

- removed police:IsSilencedWeapon, police:GetDutyPlayers, & police:GetCops as these callbacks were unused within other qbx resources or qbx-policejob
- deprecated callbacks called by other qbx resources, and added adjacent ox_lib versions
- replaced callbacks used only by qbx-policejob with ox_lib equivalent
- cleaned up some of the callback functions

feat!: callbacks registered through ox_lib

---

client/evidence.lua

Fixes this error: _@qbx-policejob/client/evidence.lua:58 No such export GetCurrentWeapon in resource ox_inventory_
Ox Reference: (https://overextended.dev/ox_inventory/Functions/Client#getcurrentweapon)

[FIX]typo fix

---

client/job.lua
fxmanifest.lua
server/main.lua

- This fixes setting vehicle extras after applying the fix on qbx-core
- Moved the callback to ox_lib

fix(client/server): fix vehicle spawn with extras

---

server/main.lua
server/storage.lua

- moved the sql calls to storage.lua. This surfaces how this resource interacts with storage and makes it easier to refactor later when doing any sort of schema change.
- also snuck in changing a table to a vec4

refactor(server): moved sql queries to storage.lua

---

client/interactions.lua

According with qbx documentation, the function GetClosestPlayer should be called without the export, it is part of the Module: utils
ref. https://qbox-project.github.io/resources/core/functions/client#getclosestplayer

Remove exports.qbx_core: from GetClosestPlayer

---

client/interactions.lua
server/main.lua

PlayerData.metadata.idead should be PlayerData.metadata.isdead to properly allow for players to be robbed while dead.
Currently you are unable to rob a dead player. This is due to the callback returning metadata that doesn't exist in the core. This change returns the correct metadata information.

:bug: Fix isPlayerDead callback

---

client/interactions.lua

Robbing players would display the inventory of the robbed player but not remove the cash and notify the player they were being robbed. This was due to a call to a nonexistent event.
Fixes removing cash from robbed players and giving it to the robber.

:bug: Robbing players fix

---

client/interactions.lua

Wrong flag used for soft cuff breaks the animation when you are uncuffed until you cancel the emote
Fixes #66
It changes cuffType from 49 to 48 and addresses the issue where the player appears cuffed after being uncuffed. Fixes #66

Fix uncuff animation bug

---

client/job.lua

Evidence and stashes are configured in ox_inventory. This code points to empty config values that generate an error on start. Removing this code fixes that

fix: remove stash and evidence

---

client/interactions.lua

lib.getClosestPlayer returns playerId, playerPed, and playerCoords. Previous utils function automagically returned a distance value. This fixes that issue.

fix: distance checks

---

client/tracker.lua

This use of lib.getClosestPlayer is incorrect. This fixes the interaction for the anklet tracker

fix: distance check

---

server/main.lua

Removes the code which drops a player for being too far away from someone.
- Should fix #97 _(there might be other issues that cause escorting to be broken, this just stops dropping players)_

fix(server/main): dropping for attempted abuse

---

client/heli.lua

When using `use_experimental_fxv2_oal 'yes'` vector expansion for natives is not supported. This causes the native to bug the resource. This fixes that issue by explicitly defining the vectors for the native.

fix(client/heli): vector expansion fix

---

client/heli.lua

Fixes freezing cam issue
Booleans are not entities.....

fix(client/heli): return entity not boolean

---

client/heli.lua

Somewhere in the conversion from qbus spaghet to qbox the variable to set the locked vehicle got lost. Tested and cam locks and unlocks as designed
Without setting the vehicleDetected to anything the cam never locks. This fixes that issue and allows the cam to lock as intended enabling police to do police like things.

fix(client/heli): set vehicleDetected

---

server/commands.lua
server/main.lua

If using qbx_prison then we should use the exports otherwise trigger the legacy event for backwards compatability
Fixes inability to jail players if using qbx_prison. Maintains backwards compatibility with other resources looking for the event trigger.

fix(server/main): use qbx_prison exports if present

---

server/main.lua

For the homies that don't run the bridge then we don't need to load the compatibility events
If you don't have the bridge enabled trying to call the QBCore export will give you an error. This corrects that.

refactor(server/main): only load compat if req

---

server/commands.lua

previous method wasnt actually setting the callsign - tested locally and works fine now
Fix callsign not setting.

fix(callsign): callsign now actually sets

---

.vscode/settings.json
client/job.lua
config/shared.lua

Part of https://github.com/Qbox-project/qbx_policejob/pull/112
The plate prefix should be in the configuration not in locales.
Now the prefix “LSPD” can have a different number of characters.

feat: police plate with dynamic prefix in config

---

server/main.lua

Fixes the display of blips when the list of players contains empty indexes.
Check discord for more details.
https://discord.com/channels/1012753553418354748/1031968831595352085/1255760678451675186

fix: updateBlips server function

---

client/main.lua
client/vehicles.lua
config/server.lua
config/shared.lua
locales/en.json
server/main.lua
types.lua

- Switches to the use of zones for vehicle spawning as it makes more sense and works better
- Use numeric for loops as we are iterating over arrays
- Send vehicle table instead of just the model so we can add the ability for vehicle customization by config
Once this PR is finalized, I'll make the same adjustments to the qbx_ambulancejob rewrite

fix(vehicles): use zones instead of targets

---

server/main.lua

Use vehicle instead of plate after this commit: https://github.com/Qbox-project/qbx_vehiclekeys/commit/146c7df4b42655ad1182536b8b95a9e133bba96b

fix(server): use new GiveKeys export properly

---

client/main.lua
config/server.lua
server/main.lua

- Fix the giving of vehicle keys
- Fix the giving of the radial menu on job changes
- Remove the `qbx_medical` dependency

fix: some minor changes

---

client/interactions.lua
config/server.lua
server/commands.lua
server/interactions.lua
server/main.lua

- Adds handcuffing/unhandcuffing with handcuffs and handcuff keys
- Adds dependency and version checking
- Fixes callsign command job checking
- Fixes the adding of vehicle mods

feat: handcuffing and dependency checks

---

client/main.lua
server/commands.lua

- Replaced player function calls with their new core export counterparts
- Removed the planned cuff and uncuff radial menu options (for now)

fix(server/commands): use new core exports

---

server/commands.lua

Fixes [an issue with sending a /911p call with multiple words/parameters](https://github.com/Qbox-project/qbx_police/issues/150).

fix: /911p multiple parameters

---

client/evidence.lua
config/client.lua

Now the ammo labels are taken from ox_inventory directly, so no need of manual configuration.

refactor: ammo labels take from ox_inventory

---

client/anpr.lua
client/interactions.lua
server/main.lua

Callback named `qbx_police:server:isPlateFlagged` is registered on the server, but on the client it's name is `police:server:isPlateFlagged`, which is then throwing an error when the vehicle drives next to the speed camera. This PR fixes this issue.
Additionally, we are preventing players from accessing their inventory while they are cuffed.

fix/feat(client): Use correct callback name / Disable inventory while cuffed
